import { ChatEvents } from "stalk-js";
import { IMessage } from "stalk-js/starter/models";
import { MessageImp, IMember } from "./models/index";
export declare const ON_MESSAGE_CHANGE = "ON_MESSAGE_CHANGE";
export declare class ChatRoomComponent implements ChatEvents.IChatServerEvents {
    private static instance;
    static getInstance(): ChatRoomComponent;
    static createInstance(datamanager: any): ChatRoomComponent;
    chatroomDelegate: (eventName: string, data: MessageImp | Array<MessageImp>) => void;
    outsideRoomDelegete: (eventName: string, data: any) => void;
    private roomId;
    getRoomId(): string;
    setRoomId(rid: string): void;
    private secure;
    private dataManager;
    private dataListener;
    private updateMessageQueue;
    constructor(dataManager: any);
    saveMessages: (chatMessages: MessageImp[], message: MessageImp) => void;
    saveToPersisted(message: MessageImp): void;
    onChat(message: MessageImp): void;
    onRoomJoin(data: any): void;
    onLeaveRoom(data: any): void;
    private messageReadTick(messageQueue, room_id);
    onMessageRead(message: IMessage): void;
    onGetMessagesReaders(dataEvent: any): void;
    getPersistentMessage(rid: string): Promise<IMessage[]>;
    getNewerMessageRecord(callback: (results: IMessage[], room_id: string) => void): Promise<void>;
    private getNewerMessages(lastMessageTime);
    getOlderMessageChunk(room_id: string): Promise<any[]>;
    getTopEdgeMessageTime(): Promise<Date>;
    private compareMessage(a, b);
    updateReadMessages(): void;
    updateWhoReadMyMessages(): Promise<void>;
    getMemberProfile(member: IMember, callback: (err, res) => void): void;
    getMessages(): Promise<any>;
    dispose(): void;
}
